### ISSUE TITLE
Cannot run on macOS Sequoia?

### ISSUE THREAD

**Issue by vrano714** [gucci-on-fleek/extractbb#1] opened 2024-11-21 13:21 UTC
Hi.
I just installed tex using Homebrew and updated using tlmgr, on 11/21 2024.

I tested compiling a simple tex file like:

```
\documentclass[dvipdfmx]{article}
\usepackage{graphicx}
\begin{document}
\includegraphics[width=5cm]{dummy.png}
\end{document}
```

and compilation ened in `Cannot determine size of graphic in dummy.xbb` error.

After looking for some workaround, I found that `extractbb.lua` may be errornous.

As far as I can confirm, `current_dir` and `choice_dir` (of following) does not match.

```
local split_dir_pattern = "^(.*)[/\\]([^/\\]-)$"
local current_dir, current_name = arg[0]:match(split_dir_pattern)
local choice_dir, choice_name = choice:match(split_dir_pattern)

if current_dir ~= choice_dir then
    print("Refusing to run a script from a different directory. Exiting.")
    os.exit(1)
end
```

Actually in my environment, 

- current_dir shows `/Library/TeX/texbin`
- choice_dir shows `/usr/local/texlive/2024/texmf-dist/scripts/extractbb`

When I comment out `if` block, compilation runs successfully.
Hope that future update solves this problem although I cannot provide any fix-up-suggestion!

(I even do not know whether this is the right place to post this issue...)

**Comment by vrano714** [comment] 2024-11-21 13:31
(and some exploring told me that v1.0.5 should resolve symlink... I'll wait this update comes to me)

**Comment by muzimuzhi** [comment] 2024-11-21 14:26
I tried v1.0.5 locally on macOS 14.7.1 and basicTeX 2024, and it still failed with error
```
! extractbb ERROR: Refusing to run a script from a different directory.
```

Adding some debugging log, I get
```
$ extractbb -B cropbox -O test.pdf
[before resolving symlinks]
  current_dir = /Library/TeX/texbin
  choice_dir = /usr/local/texlive/2024basic/texmf-dist/scripts/extractbb
[after resolving symlinks]
  current_dir = Distributions/Programs/texbin
/Library/TeX/texbin/extractbb:96: attempt to concatenate a nil value (local 'choice_dir')
```

It reveals several problems in relevant code in v1.0.5:
https://github.com/gucci-on-fleek/extractbb/blob/85562f4326402c1d01d8de1e241b7539f6f18d25/source/extractbb-chooser.lua#L73-L85

For each of `current_dir` and `choice_dir`:
- when it's a symlink, its target may be a relative path, which itself may even still be a symlink.
- when it's not a symlink, calling `lfs.symlinkattributes(filepath, "target")` returns `nil`.

Seems [`lfs`](https://lunarmodules.github.io/luafilesystem/manual.html) doesn't have direct support for obtaining fully resolved path of a file and `devv.ai` gave a [lengthy Lua snippet](https://devv.ai/search?threadId=e4mf8c6ms3r4).

**Comment by muzimuzhi** [comment] 2024-11-21 15:17
BTW the [test suite of `l3graphics`](https://github.com/latex3/latex3/tree/develop/l3experimental/l3graphics/testfiles) may be used as one of the test cases for `extractbb`. Currently the `extractbb` v1.0.4 failed the `l3graphics` tests, see [this job log](https://github.com/muzimuzhi/latex3/actions/runs/11952138386/job/33317240209).

**Comment by gucci-on-fleek** [comment] 2024-11-21 22:13
Looks like I had the exact same problem with an earlier version of the script:

> extractbb: put in dvipdfmx package since that is where it is needed; do not make "incorrect location" check since it fails on MacTeX setup; https://tug.org/pipermail/tex-live/2024-July/050719.html
> ```diff
> diff --git a/Master/texmf-dist/scripts/texlive/extractbb.lua b/Master/texmf-dist/scripts/texlive/extractbb.lua
> index 9c5ab513a71..db63bd01bc4 100755
> --- a/[Master/texmf-dist/scripts/texlive/extractbb.lua](https://git.texlive.info/texlive/tree/Master/texmf-dist/scripts/texlive/extractbb.lua?id=157f4b8ca0dfcec0e44b6e4d93a29d93870a8860)
> +++ b/[Master/texmf-dist/scripts/texlive/extractbb.lua](https://git.texlive.info/texlive/tree/Master/texmf-dist/scripts/texlive/extractbb.lua?id=81b7eebce64690799db520894f15df5ac414e4bc)
> @@ -185,9 +185,11 @@ if not resolved_script_path then
>      error("Empty resolved script path")
>  end
>  
> -if (script_dir ~= interpreter_dir) and (script_path ~= resolved_script_path) then
> -    error("The script is in an incorrect location: " .. script_dir)
> -end
> +-- But on Macs we get /Library/TeX/texbin. What to do?
> +-- (Frank msg to tex-live 8jul24.)
> +-- if (script_dir ~= interpreter_dir) and (script_path ~= resolved_script_path) then
> +--     error("The script is in an incorrect location: " .. script_dir)
> +-- end
>  
>  if script_name ~= SCRIPT_NAME then
>      error("Incorrect script name: " .. script_name)
> ```
> _https://git.texlive.info/texlive/commit/Master/texmf-dist/scripts/texlive/extractbb.lua?id=81b7eebce64690799db520894f15df5ac414e4bc_

I switched to a new path checking strategy in db5c8ee65f5f7f784253dac7c9712ccd06ca6f0d, so it should hopefully be fixed in [v1.0.6](https://github.com/gucci-on-fleek/extractbb/releases/tag/v1.0.6).

Anyways, thanks for the report, and sorry for breaking `extractbb` (again).

**Closed as completed** 2024-11-21 22:16 UTC

**Comment by gucci-on-fleek** [comment] 2024-11-21 22:19
@muzimuzhi 

> BTW the [test suite of `l3graphics`](https://github.com/latex3/latex3/tree/develop/l3experimental/l3graphics/testfiles) may be used as one of the test cases for `extractbb`. Currently the `extractbb` v1.0.4 failed the `l3graphics` tests, see [this job log](https://github.com/muzimuzhi/latex3/actions/runs/11952138386/job/33317240209).

That won't quite work here unfortunately. The script worked fine from `l3build` since there I was calling it directly from the `texmf/scripts` directory; it only failed when the script was placed in the `bin/<platform>` directory, which isn't something that I can really test with `l3build`.

But that being said, I am interested in more test files. Right now I've just copied in the sample images from the `mwe` package, but if you know of any “interesting” images (images that have weird technical details), please email them to me or open a PR to add them to the [`tests/`](https://github.com/gucci-on-fleek/extractbb/tree/master/tests) folder.

**Comment by muzimuzhi** [comment] 2024-11-21 22:33
@gucci-on-fleek I can confirm v1.0.6 passed the tests for `l3graphics`. Many thanks!
